### ISSUE TITLE
Image normalization correct?

### ISSUE THREAD

**Issue by NRauschmayr** [marcbelmont/gan-image-similarity#2]
I tried out your code on a different dataset and it works quite nicely. Just one question: why did you choose the following normalization for the images?  
image = image * (1. / 255) - 0.5
This produces normalized values in the range [-0.5,0.5], but shouldn't the normalized values be in the range of either [-1,1] or [0,1]?

**Comment by marcbelmont** [comment]
You are right. Proper normalization would be `image = (image - mean) / std` with `mean` and `std` calculated over the entire dataset. It could maybe speed up convergence a little but I don't think it will have a big impact. I'm happy to merge your pull request if you feel like doing the change.
